name: Deploy the frontend

on:
  push:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          build-args:
            - DATABASE_URL=${{ secrets.DATABASE_URL }}
          push: true
          tags: manojofficialmj/nextjs-application:${{ github.sha }}

      - name: Deploy to the VM         ## This step to deploy to the VM
          run: |
            echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
            chmod 700 /home/runner/ssh_key
            ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@64.227.169.180 -t "docker stop user_frontend && docker run --name user_frontend-d -p 3000:3000 manojofficialmj/nextjs-application:${{ github.sha }}"